name: Build platforms

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.21"
        # https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63
        platform:
          # - aix/ppc64
          # - android/386
          - android/amd64
          # - android/arm
          - android/arm64
          - darwin/amd64
          - darwin/arm64
          - dragonfly/amd64
          - freebsd/386
          - freebsd/amd64
          - freebsd/arm
          - freebsd/arm64
          - illumos/amd64
          # - ios/amd64
          # - ios/arm64
          # - js/wasm
          - linux/386
          - linux/amd64
          - linux/arm
          - linux/arm64
          - linux/mips
          - linux/mips64
          - linux/mips64le
          - linux/mipsle
          - linux/ppc64
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x
          - netbsd/386
          - netbsd/amd64
          - netbsd/arm
          - netbsd/arm64
          - openbsd/386
          - openbsd/amd64
          - openbsd/arm
          - openbsd/arm64
          # - openbsd/mips64
          # - plan9/386
          # - plan9/amd64
          # - plan9/arm
          - solaris/amd64
          - windows/386
          - windows/amd64
          - windows/arm
          - windows/arm64
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.version }}
    - name: Set GOOS and GOARCH
      run: |
        echo "GOOS=$(echo ${{ matrix.platform }} | cut -d/ -f1)" >> $GITHUB_ENV
        echo "GOARCH=$(echo ${{ matrix.platform }} | cut -d/ -f2)" >> $GITHUB_ENV
    - run: go build
